### PR TITLE
isolated if- parse bug

### LINKED ISSUE #166: One line ifs parse outside of elements
This can produce a parse error:

```html
<p>gif-jpg-png</p>
```

Note the string "if-" is present in that sample code.

### PR DESCRIPTION
**Pull request by w00tedness**
Fixed #166 

Implemented recursive match so nesting works whether or not 'if-' should be parsed.

Added some test templates and their accompanying unit tests to make sure other features do not break:
 * `test/templates/conditionals/ifOutsideIf.html`
 * ` test/templates/conditionals/nestedIfOutsideIf.html`
 * `test/templates/conditionals/oneLineIfOutsideIf.html`
 * `test/templates/conditionals/oneLineIfOutsideIfReverse.html` 
 * `test/templates/conditionals/varIfOutsideIf.html`

### CODE REVIEW

File: teddy.js [hunk 1]
```diff
@@ -669,8 +669,13 @@
         if (renderedTemplate.indexOf('if-') > -1) {
           onelines = renderedTemplate.match(/[^<]*?if-[^>]+/g);
           l = onelines ? onelines.length : 0;
-
           for (i = 0; i < l; i++) {
+
+            // completely ignore the matches if they contain any angle brackets.
+            if (onelines[i].indexOf('>') > -1 || onelines[i].indexOf('<') > -1) {
```
Comment (alallier) [inline teddy.js]: This is an interesting way of solving it haha.

**Comment by kethinov** [comment]
fix the coverage

**Comment by kethinov** [comment]
i'm honestly surprised this two passes approach isn't crazy slow

but since it seems to do what it's supposed to do, i'll take it
