### PR TITLE
Fix windows tests

### LINKED ISSUE #661: Client tests broken in Windows

### PR DESCRIPTION
**Pull request by awidener3**
Update filepaths for tests to work in playwright

`test\template\misc.html` -> `test/template/misc.html`

closes #661

### CODE REVIEW

File: test/loaders/loaderUtils.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ export function registerTemplates (teddy, dir) {
       registerTemplates(teddy, filePath)
     } else {
       // remove unneeded path and filetype
-      const path = filePath.replace('test/templates/', '').replace('.html', '')
+      const path = filePath.replaceAll('\\', '/').replace('test/templates/', '').replace('.html', '')
```
Comment (kethinov) [inline test/loaders/loaderUtils.js:49]: i think `path.normalize` would be better using the node path module

**Review by kethinov — CHANGES_REQUESTED** [review]

**Review by kethinov — APPROVED** [review]
